# nc_console.py — CLI for NeuroConsole (NC)
# Usage:
#   nc <file.nc>
#   nc <https://site/path/file.nc>
#   nc --learn
#   nc --learn basics
# Options:
#   --base <path_or_url_dir>
#   --libs <path> (repeatable)
#   --allow-http
#   --allow-private

from __future__ import annotations

import os
import sys
import argparse
import shutil
import subprocess
import tempfile
from pathlib import Path

# ------------------------------------------------------------
# UTF-8 FIX (Windows + QProcess / ncw):
# Prevent: "charmap codec can't encode characters ..."
# Must be BEFORE importing nc (because nc/prints may happen early)
# ------------------------------------------------------------
os.environ.setdefault("PYTHONIOENCODING", "utf-8")
os.environ.setdefault("PYTHONUTF8", "1")
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

from urllib.parse import urlparse  # (kept, even if not used)

import nc as nc


def is_url(s: str) -> bool:
    return s.startswith("https://") or s.startswith("http://")


def read_text_from_target(target: str, policy: nc.NCPolicy) -> str:
    if is_url(target):
        return nc._fetch_url_text(target, policy)
    # local file
    with open(target, "r", encoding="utf-8", errors="replace") as f:
        return f.read()


def compute_base(target: str) -> str:
    if is_url(target):
        # base = url directory
        return target.rsplit("/", 1)[0] + "/"
    # local file directory
    return os.path.dirname(os.path.abspath(target)) or os.getcwd()


def _safe_exe_name_from_target(target: str) -> str:
    base = os.path.basename(target)
    if base.lower().endswith(".nc"):
        base = base[:-3]
    base = base.strip() or "nc_app"
    cleaned = []
    for ch in base:
        cleaned.append(ch if (ch.isalnum() or ch in ("_", "-", ".")) else "_")
    return "".join(cleaned).strip("._") or "nc_app"

def build_exe_from_nc(target: str, policy: nc.NCPolicy, base: str, search_paths: list[str], enable_ui: bool = True) -> str:
    if is_url(target):
        raise RuntimeError("--exe currently supports local .nc files only.")

    src_path = os.path.abspath(target)
    if not os.path.isfile(src_path):
        raise FileNotFoundError(src_path)

    exe_name = _safe_exe_name_from_target(src_path)
    pyinstaller_exe = shutil.which("pyinstaller")
    pyinstaller_cmd = [pyinstaller_exe] if pyinstaller_exe else [sys.executable, "-m", "PyInstaller"]

    build_root = Path(base if (base and not is_url(base)) else os.path.dirname(src_path)).resolve()
    output_root = build_root / "nc_exe_build"
    output_root.mkdir(parents=True, exist_ok=True)

    launcher_code = f"""# Auto-generated by nc --exe
from __future__ import annotations
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
EXTRA_PATHS = {search_paths!r}
for _p in list(EXTRA_PATHS):
    if _p and _p not in sys.path:
        sys.path.insert(0, _p)
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import nc as nc

def main() -> int:
    try:
        nc.run_file(
            {src_path!r},
            policy=nc.NCPolicy(
                allow_http={bool(policy.allow_http)!r},
                allow_private_hosts={bool(policy.allow_private_hosts)!r},
                max_module_bytes={int(policy.max_module_bytes)!r},
                url_timeout_sec={int(policy.url_timeout_sec)!r},
                max_import_depth={int(policy.max_import_depth)!r},
                max_steps={int(policy.max_steps)!r},
                max_expr_len={int(policy.max_expr_len)!r},
                data_dir={policy.data_dir!r},
            ),
            enable_ui={bool(enable_ui)!r},
            extra_paths=EXTRA_PATHS,
        )
        return 0
    except Exception as e:
        print("NC EXE ERROR:", str(e))
        return 1

if __name__ == "__main__":
    raise SystemExit(main())
"""

    with tempfile.TemporaryDirectory(prefix="nc_exe_") as tmp:
        launcher = Path(tmp) / f"{exe_name}_launcher.py"
        launcher.write_text(launcher_code, encoding="utf-8")

        cmd = pyinstaller_cmd + [
            "--noconfirm",
            "--clean",
            "--onefile",
            "--name", exe_name,
            "--distpath", str(output_root / "dist"),
            "--workpath", str(output_root / "build"),
            "--specpath", str(output_root / "spec"),
            str(launcher),
        ]

        proc = subprocess.run(cmd, capture_output=True, text=True)
        if proc.returncode != 0:
            stderr = (proc.stderr or "").strip()
            stdout = (proc.stdout or "").strip()
            details = stderr or stdout or "PyInstaller failed"
            if "No module named PyInstaller" in details:
                raise RuntimeError("PyInstaller is not installed. Install it with: pip install pyinstaller") from None
            raise RuntimeError(details)

    exe_path = output_root / "dist" / f"{exe_name}.exe"
    if not exe_path.is_file():
        raise RuntimeError(f"Build finished but EXE was not found: {exe_path}")
    return str(exe_path)



def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(prog="nc", add_help=True)
    p.add_argument("target", nargs="?", help="Path to .nc file or URL to .nc")
    p.add_argument("--learn", nargs="?", const="", help="Start learn mode (optional topic)")
    p.add_argument("--base", default=None, help="Base folder/URL for resolving relative imports")
    p.add_argument("--libs", action="append", default=[], help="Extra library search path (repeatable)")
    p.add_argument("--allow-http", action="store_true", help="Allow http:// imports (default: https only)")
    p.add_argument("--allow-private", action="store_true", help="Allow private/localhost URL imports (default blocked)")
    p.add_argument("--no-ui", action="store_true", help="Disable __TWIN__ UI output")
    p.add_argument("--no-log", action="store_true", help="Disable step logs")
    p.add_argument("--exe", action="store_true", help="Build the local .nc file into a Windows .exe via PyInstaller")

    args = p.parse_args(argv)

    # Learn mode
    if args.learn is not None:
        topic = args.learn.strip() or None
        nc.run_learn(topic)
        return 0

    if not args.target:
        p.print_help()
        return 2

    policy = nc.NCPolicy(
        allow_http=bool(args.allow_http),
        allow_private_hosts=bool(args.allow_private),
    )

    target = args.target

    # Allow accidental URL/file fragments like "wormpad.nc#"
    target = target.split("#", 1)[0]

    # For local files: allow calling without .nc extension
    if (not is_url(target)) and (not target.lower().endswith(".nc")):
        if os.path.isfile(target + ".nc"):
            target = target + ".nc"

    text = read_text_from_target(target, policy)

    base = args.base or compute_base(target)

    search_paths = []
    # default search paths for local usage
    if not is_url(base):
        search_paths.extend([base, os.path.join(base, "libs")])
    # additional libs from args
    for lp in args.libs:
        search_paths.append(lp)

    # If user disabled UI/logging, patch by adding a tiny override at end
    if args.no_log:
        text = text + "\n\n# __NC_CONSOLE_NO_LOG__\n"

    try:
        if args.exe:
            exe_path = build_exe_from_nc(
                target=target,
                policy=policy,
                base=base,
                search_paths=search_paths,
                enable_ui=(not args.no_ui),
            )
            print("NC EXE:", exe_path)
            return 0

        nc.run_text(
            text,
            base=base,
            extra_paths=search_paths,
            policy=policy,
            enable_ui=(not args.no_ui),
            source_name=(target if is_url(target) else os.path.abspath(target)),
        )
        return 0
    except Exception as e:
        print("NC ERROR:", str(e))
        return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
